### ISSUE TITLE
SqlLite

### ISSUE THREAD

**Issue by JakalNax** [cloverstudio/Spika-iOS#12]
We still not sqllite local db? Application consumes too much traffic.

**Comment by TTMTT** [comment]
@JakalNax 
Hello,
We will make this feature in the future..

**Comment by JakalNax** [comment]
How about integration with address book like what's up.

**Comment by TTMTT** [comment]
@JakalNax 
we can't do that.. becoz the loign system via email not phone number
and all accounts in spika by email ..
